"""Add extraction tracking fields to QuestionDocument model

Revision ID: 2155839e3385
Revises: 
Create Date: 2025-06-08 11:59:47.845040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2155839e3385'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extraction_progress', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('extraction_message', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('total_pages', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('processed_pages', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('extraction_started_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_documents', schema=None) as batch_op:
        batch_op.drop_column('extraction_started_at')
        batch_op.drop_column('processed_pages')
        batch_op.drop_column('total_pages')
        batch_op.drop_column('extraction_message')
        batch_op.drop_column('extraction_progress')

    # ### end Alembic commands ###
